### ISSUE TITLE
[README] Jadegame.com link is down and possible fix

### ISSUE THREAD

**Issue by hpsaturn** [brizzly/jsEmu48#4]
## Summary

First of all, your work is amazing! I am a big fan of the HP48. While looking for possible emulators, I found this repository and noticed that your HP48 page is down. I believe it is a wonderful piece of HP48 history.

If it would be helpful, I own the domain https://hpsaturn.com. I can set up a CNAME record to redirect it to any host you prefer. Additionally, I can host your page on my project server at https://canair.io/.

Please let me know if you are interested!

**Comment by brizzly** [comment]
Hi hpsaturn, 
Thank you for your message !
The new link is here: https://jmapp.com/jsemu48/

**Comment by hpsaturn** [comment]
Oh! thanks, but also I said that around these content that is missing:
https://web.archive.org/web/20190705110143/http://www.jadegame.com/games/hp48

**Comment by brizzly** [comment]
Thank you hpsaturn for reporting this broken link!
I managed to re-upload it here: https://jmapp.com/games/hp48/
PS: can you tell me where does this broken link came from ?

**Comment by hpsaturn** [comment]
mmm, yes, I was confused were, but I found the source of the problem. In the README of the people of x48ng they have some references, but they maybe did a mistake and them put you a fork instead your jsemu48, here:
https://github.com/gwenhael-le-moine/x48ng?tab=readme-ov-file (at the end),
this fork referenced there has the problem.
Maybe only we should notify this or push a PR, I guess.

**Comment by brizzly** [comment]
Good point!
I agree with you, notify then is fine I guess, but it's not very important though :)
